# src/verses.py
import datetime
from zoneinfo import ZoneInfo

MX = ZoneInfo("America/Mexico_City")

# Para que no se repita por ~60 días:
# index = (date.toordinal() + offset) % 60
OFFSETS = {"morning": 7, "noon": 23, "night": 41}

SLOTS = {
    "morning": {
        "tag": "DIOS TE HABLA HOY",
        "headline": "Gracias por este nuevo día",
        "items": [
            {"verse": "Hoy es un regalo de Dios: elige gozo y fe.", "ref": "Salmo 118:24", "theme": "gratitud y propósito", "angle": "Dios te dio este día como una nueva oportunidad de volver a empezar con Él."},
            {"verse": "Cada mañana hay misericordia nueva para ti.", "ref": "Lamentaciones 3:22-23", "theme": "misericordia y renovación", "angle": "Si amaneciste, Dios no terminó contigo: hoy puedes regresar."},
            {"verse": "Confía en Dios con todo tu corazón: Él endereza tu camino.", "ref": "Proverbios 3:5-6", "theme": "confianza y dirección", "angle": "Tu mente puede estar confundida, pero Dios sabe guiarte paso a paso."},
            {"verse": "Dios escucha tu mañana: habla con Él primero.", "ref": "Salmo 5:3", "theme": "oración y prioridad", "angle": "Antes del ruido, vuelve a la presencia: ahí se ordena el corazón."},
            {"verse": "Los que esperan en Dios renuevan fuerzas para seguir.", "ref": "Isaías 40:31", "theme": "fuerza y esperanza", "angle": "Aunque estés cansado, Dios puede darte fuerzas reales hoy."},
            {"verse": "Busca primero a Dios y lo demás se acomoda.", "ref": "Mateo 6:33", "theme": "prioridades", "angle": "Cuando Dios está primero, tu vida deja de ir a la deriva."},
            {"verse": "Dios te muestra el camino y te sostiene con amor.", "ref": "Salmo 143:8", "theme": "guía y amor", "angle": "Si te sientes lejos, su voz te vuelve a llamar con ternura."},
            {"verse": "Presenta tus cargas a Dios y su paz te guardará.", "ref": "Filipenses 4:6-7", "theme": "ansiedad y paz", "angle": "No estás hecho para cargarlo todo: entrégalo en oración."},
            {"verse": "Tu ayuda viene del Señor, no de tu fuerza.", "ref": "Salmo 121:1-2", "theme": "dependencia de Dios", "angle": "Cuando ya no puedes, Dios sigue pudiendo."},
            {"verse": "Sacia tu alma con alegría y gracia desde temprano.", "ref": "Salmo 90:14", "theme": "gozo y gratitud", "angle": "Dios puede cambiar el tono de tu día desde la mañana."},
            {"verse": "Pon tus planes en manos de Dios y camina en paz.", "ref": "Proverbios 16:3", "theme": "rendición", "angle": "La paz crece cuando sueltas el control y confías."},
            {"verse": "Sé valiente: Dios va contigo hoy.", "ref": "Josué 1:9", "theme": "valentía", "angle": "No es ausencia de miedo: es avanzar confiando en Dios."},
            {"verse": "En Cristo puedes comenzar de nuevo.", "ref": "2 Corintios 5:17", "theme": "nuevo comienzo", "angle": "Tu historia no termina en tu error: Dios restaura."},
            {"verse": "Entrega tu camino al Señor y confía en Él.", "ref": "Salmo 37:5", "theme": "confianza", "angle": "Dios sabe llevarte a un lugar mejor que tu ansiedad."},
            {"verse": "No temas: Dios te fortalece y te sostiene.", "ref": "Isaías 41:10", "theme": "seguridad", "angle": "Dios no te abandona cuando estás débil: te afirma."},
            {"verse": "Dios es tu refugio presente en la dificultad.", "ref": "Salmo 46:1", "theme": "refugio", "angle": "Tu problema es real, pero Dios es más real aún."},
            {"verse": "Dios puede sacar bien aun de lo duro.", "ref": "Romanos 8:28", "theme": "propósito en pruebas", "angle": "Lo que te dolió no define tu final: Dios lo transforma."},
            {"verse": "Acércate con confianza: hay gracia para ti.", "ref": "Hebreos 4:16", "theme": "gracia", "angle": "No necesitas esconderte: Dios recibe al que vuelve."},
            {"verse": "Dios está cerca del corazón quebrantado.", "ref": "Salmo 34:18", "theme": "consuelo", "angle": "Si estás roto por dentro, Dios no te desprecia: te abraza."},
            {"verse": "Con Dios, tu vida da fruto; sin Él, te secas.", "ref": "Juan 15:5", "theme": "permanecer", "angle": "Volver a Dios es volver a la fuente."},
            {"verse": "Haz todo en el nombre del Señor, con gratitud.", "ref": "Colosenses 3:17", "theme": "vida con sentido", "angle": "Tu rutina se vuelve propósito cuando Dios está en el centro."},
            {"verse": "Que tus palabras y pensamientos agraden a Dios.", "ref": "Salmo 19:14", "theme": "pureza interior", "angle": "El cambio real empieza en lo que alimentas en secreto."},
            {"verse": "Cuida tu corazón: de ahí nace tu vida.", "ref": "Proverbios 4:23", "theme": "cuidado del corazón", "angle": "Tu dirección cambia cuando tu corazón se ordena."},
            {"verse": "El llanto dura, pero la alegría vuelve con Dios.", "ref": "Salmo 30:5", "theme": "esperanza", "angle": "La noche no es eterna: Dios trae mañana."},
            {"verse": "Dios te acompaña aun en aguas profundas.", "ref": "Isaías 43:2", "theme": "compañía de Dios", "angle": "No estás solo en tu proceso: Dios está contigo."},
            {"verse": "Con Dios a tu lado, tu corazón se afirma.", "ref": "Salmo 16:8", "theme": "estabilidad", "angle": "Cuando Dios está cerca, el miedo pierde fuerza."},
            {"verse": "Dios es bueno con quien lo busca de verdad.", "ref": "Lamentaciones 3:25", "theme": "búsqueda", "angle": "Volver no es complicado: es sincero."},
            {"verse": "El Señor es tu luz: no temas.", "ref": "Salmo 27:1", "theme": "confianza", "angle": "Tu oscuridad no apaga la luz de Dios."},
            {"verse": "Dios puede hacer más de lo que imaginas.", "ref": "Efesios 3:20", "theme": "fe", "angle": "No limites a Dios por tu pasado."},
            {"verse": "Dios te llena de esperanza y paz al creer.", "ref": "Romanos 15:13", "theme": "esperanza", "angle": "La fe no es emoción: es confiar aunque duela."},
            {"verse": "Dios es tu pastor: no te faltará lo esencial.", "ref": "Salmo 23:1", "theme": "provisión", "angle": "Si vuelves al Pastor, encuentras descanso."},
            {"verse": "Ven a Jesús y recibe descanso verdadero.", "ref": "Mateo 11:28-30", "theme": "descanso", "angle": "Dios no te exige llegar perfecto: te invita a venir."},
            {"verse": "Dios te amó primero: ese amor te sostiene.", "ref": "Juan 3:16", "theme": "amor de Dios", "angle": "Tu valor no depende de tu rendimiento: depende de su amor."},
            {"verse": "Echa tu ansiedad sobre Dios: Él cuida de ti.", "ref": "1 Pedro 5:7", "theme": "ansiedad", "angle": "No cargues lo que Dios quiere cargar contigo."},
            {"verse": "Dios es bueno y listo para perdonar.", "ref": "Salmo 86:5", "theme": "perdón", "angle": "No te quedes lejos por vergüenza: vuelve por gracia."},
            {"verse": "Dios se acerca al que lo busca con sinceridad.", "ref": "Salmo 145:18", "theme": "cercanía", "angle": "Si hoy lo llamas de corazón, Él responde."},
            {"verse": "Dios guarda en paz la mente que confía.", "ref": "Isaías 26:3", "theme": "paz mental", "angle": "La paz crece cuando tu mente se ancla en Dios."},
            {"verse": "Espera en Dios: Él es tu roca.", "ref": "Salmo 62:5-6", "theme": "paciencia", "angle": "No tomes decisiones desde el pánico: espera en Dios."},
            {"verse": "Dios es refugio: di con fe que Él te cubre.", "ref": "Salmo 91:1-2", "theme": "protección", "angle": "Tu casa y tu vida pueden descansar bajo su cuidado."},
            {"verse": "Dios te dio poder, amor y dominio propio.", "ref": "2 Timoteo 1:7", "theme": "valentía y carácter", "angle": "No estás destinado a vivir dominado por el miedo."},
            {"verse": "Dios te levanta del lodo y afirma tus pasos.", "ref": "Salmo 40:1-2", "theme": "restauración", "angle": "Dios no solo te perdona: te vuelve a levantar."},
            {"verse": "Espera en Dios: tu alma vuelve a respirar.", "ref": "Salmo 42:11", "theme": "ánimo", "angle": "Tu corazón puede aprender a esperar con fe."},
            {"verse": "La Palabra de Dios ilumina tu camino hoy.", "ref": "Salmo 119:105", "theme": "dirección", "angle": "Cuando no sabes qué hacer, vuelve a la Palabra."},
            {"verse": "El nombre del Señor es torre segura.", "ref": "Proverbios 18:10", "theme": "seguridad", "angle": "Hay refugio cuando llamas el nombre de Dios."},
            {"verse": "Dios examina tu corazón y te guía por su camino.", "ref": "Salmo 139:23-24", "theme": "transformación", "angle": "La sanidad inicia cuando eres honesto delante de Dios."},
            {"verse": "Busca al Señor hoy: está cerca de ti.", "ref": "Isaías 55:6", "theme": "búsqueda", "angle": "Volver empieza con una decisión: buscarlo hoy."},
            {"verse": "Dios no te dejará: permanece contigo.", "ref": "Hebreos 13:5", "theme": "fidelidad", "angle": "Aunque sientas soledad, Dios sigue ahí."},
            {"verse": "Sé fuerte: Dios va delante de ti.", "ref": "Deuteronomio 31:6", "theme": "seguridad", "angle": "No caminas solo: Dios abre camino."},
            {"verse": "Dios es grande: tu vida tiene propósito.", "ref": "Salmo 8:1", "theme": "asombro y adoración", "angle": "Cuando miras a Dios, tu problema se vuelve manejable."},
            {"verse": "Bendice al Señor: no olvides sus bondades.", "ref": "Salmo 103:2-5", "theme": "gratitud", "angle": "Recordar lo que Dios hizo fortalece tu fe hoy."},
            {"verse": "Alégrate, ora y agradece: Dios guía tu día.", "ref": "1 Tesalonicenses 5:16-18", "theme": "hábitos espirituales", "angle": "Tu día cambia cuando tu corazón se vuelve agradecido."},
            {"verse": "Mi alma te busca temprano, Señor.", "ref": "Salmo 63:1", "theme": "búsqueda", "angle": "Si vuelves temprano a Dios, vuelves más firme."},
            {"verse": "Tu amor es grande: me sostengo en Él.", "ref": "Salmo 57:10", "theme": "amor", "angle": "Cuando el amor de Dios te llena, la culpa se suelta."},
            {"verse": "Sé constante y paciente: Dios te fortalece.", "ref": "Romanos 12:12", "theme": "perseverancia", "angle": "No renuncies hoy: Dios te sostiene en el proceso."},
            {"verse": "Jesús te da paz: no vivas dominado por temor.", "ref": "Juan 14:27", "theme": "paz", "angle": "La paz de Dios no depende de circunstancias perfectas."},
            {"verse": "Cuando tengo miedo, confío en Dios.", "ref": "Salmo 56:3", "theme": "confianza", "angle": "El miedo no manda: la fe te guía."},
            {"verse": "En quietud está tu salvación; confía.", "ref": "Isaías 30:15", "theme": "calma y fe", "angle": "No corras por ansiedad: vuelve a la quietud con Dios."},
            {"verse": "Dios es tu fuerza aunque tu corazón se canse.", "ref": "Salmo 73:26", "theme": "fortaleza", "angle": "Dios sostiene lo que tú ya no puedes sostener."},
            {"verse": "Fortalécete en el Señor y en su poder.", "ref": "Efesios 6:10", "theme": "fortaleza espiritual", "angle": "Tu batalla no se gana solo con ganas: se gana con Dios."},
            {"verse": "El que se aferra a Dios florece aun en tiempos duros.", "ref": "Salmo 1:2-3", "theme": "disciplina y fruto", "angle": "Si vuelves a la Palabra, tu vida se vuelve estable."},
        ],
    },

    "noon": {
        "tag": "RETOMA EL CAMINO",
        "headline": "Fuerza para volver",
        "items": [
            {"verse": "Dios te llama a volver: deja el mal y regresa.", "ref": "Isaías 55:7", "theme": "arrepentimiento", "angle": "No es condena: es una puerta abierta para regresar."},
            {"verse": "Acércate a Dios y Él se acercará a ti.", "ref": "Santiago 4:8", "theme": "regreso", "angle": "Un paso hacia Dios cambia la dirección de tu día."},
            {"verse": "Dios perdona cuando confiesas de verdad.", "ref": "1 Juan 1:9", "theme": "perdón", "angle": "La culpa se rompe cuando traes todo a la luz."},
            {"verse": "No te conformes: renueva tu mente.", "ref": "Romanos 12:2", "theme": "transformación", "angle": "El cambio empieza cuando cambias lo que alimentas en la mente."},
            {"verse": "La verdad te hace libre de lo que te ata.", "ref": "Juan 8:32", "theme": "libertad", "angle": "Dios no quiere que vivas esclavo: quiere restaurarte."},
            {"verse": "Hoy es el día para reconciliarte con Dios.", "ref": "2 Corintios 6:2", "theme": "urgencia espiritual", "angle": "No pospongas tu regreso: hoy cuenta."},
            {"verse": "Dios resiste al orgulloso, da gracia al humilde.", "ref": "Santiago 4:6", "theme": "humildad", "angle": "Bajar el orgullo abre la puerta a la gracia."},
            {"verse": "Vuelve a tu primer amor: no te apagues.", "ref": "Apocalipsis 2:4-5", "theme": "volver al amor", "angle": "Dios no te regaña para hundirte: te llama para levantarte."},
            {"verse": "Perdona como Dios te perdonó a ti.", "ref": "Efesios 4:32", "theme": "perdón", "angle": "Retomar el camino incluye soltar rencor."},
            {"verse": "No devuelvas mal: vence con el bien.", "ref": "Romanos 12:21", "theme": "carácter", "angle": "Dios te llama a responder distinto, no por orgullo, por fe."},
            {"verse": "Camina en la luz y tu vida se limpia.", "ref": "1 Juan 1:7", "theme": "integridad", "angle": "Salir de la oscuridad es el primer paso para sanar."},
            {"verse": "Cristo te fortalece para levantarte hoy.", "ref": "Filipenses 4:13", "theme": "fortaleza", "angle": "Tu fuerza no es tu ánimo: es Cristo sosteniéndote."},
            {"verse": "Dios te da salida cuando llega la tentación.", "ref": "1 Corintios 10:13", "theme": "tentación", "angle": "No estás obligado a caer: hay salida con Dios."},
            {"verse": "Despierta y vuelve: Cristo te alumbrará.", "ref": "Efesios 5:14", "theme": "despertar espiritual", "angle": "No sigas dormido por dentro: hoy es para regresar."},
            {"verse": "Si caíste, levántate: Dios sostiene al que tropieza.", "ref": "Proverbios 24:16", "theme": "perseverancia", "angle": "Caer no es el final si decides levantarte con Dios."},
            {"verse": "Dios sana al corazón roto y venda heridas.", "ref": "Salmo 147:3", "theme": "sanidad", "angle": "Tu dolor no te cancela: Dios lo transforma."},
            {"verse": "Tu boca puede traer vida: habla con sabiduría.", "ref": "Proverbios 18:21", "theme": "palabras", "angle": "Retomar el camino también es ordenar lo que dices."},
            {"verse": "Guarda tu corazón de la envidia y del enojo.", "ref": "Proverbios 14:30", "theme": "emociones", "angle": "Dios quiere curar lo que te envenena por dentro."},
            {"verse": "El Señor es compasivo: no te rechaza al volver.", "ref": "Salmo 103:8", "theme": "misericordia", "angle": "La gracia de Dios es más grande que tu vergüenza."},
            {"verse": "Cristo te hizo libre: no vuelvas a cadenas.", "ref": "Gálatas 5:1", "theme": "libertad", "angle": "No regreses a lo que te destruye: vuelve a Dios."},
            {"verse": "Haz el bien hoy: no lo pospongas.", "ref": "Gálatas 6:9", "theme": "constancia", "angle": "Dios honra la obediencia diaria, no solo emociones."},
            {"verse": "Si tu corazón te acusa, Dios es mayor.", "ref": "1 Juan 3:20", "theme": "culpa", "angle": "Tu acusación interna no tiene la última palabra."},
            {"verse": "Dios te llama por tu nombre: no temas.", "ref": "Isaías 43:1", "theme": "identidad", "angle": "No eres tu caída: eres llamado por Dios."},
            {"verse": "Crea en mí un corazón limpio, Señor.", "ref": "Salmo 51:10", "theme": "limpieza interior", "angle": "Retomar el camino es pedir un corazón nuevo."},
            {"verse": "El que se humilla será levantado por Dios.", "ref": "1 Pedro 5:6", "theme": "humildad", "angle": "Bajar la cabeza ante Dios levanta tu vida."},
            {"verse": "No apagues el Espíritu: vuelve a escuchar.", "ref": "1 Tesalonicenses 5:19", "theme": "sensibilidad espiritual", "angle": "Dios sigue hablando; tu corazón puede volver a oír."},
            {"verse": "Vive sobrio: tu vida vale demasiado.", "ref": "1 Pedro 5:8", "theme": "vigilancia", "angle": "Lo que toleras hoy puede destruirte mañana: vuelve."},
            {"verse": "La paz empieza cuando haces lo correcto.", "ref": "Isaías 32:17", "theme": "obediencia", "angle": "Dios no solo te consuela: también te reordena."},
            {"verse": "Dios te enseña el camino para que vivas.", "ref": "Salmo 32:8", "theme": "dirección", "angle": "Si no sabes qué hacer, Dios sí sabe."},
            {"verse": "El amor cubre: suelta el pleito y vuelve a amar.", "ref": "1 Pedro 4:8", "theme": "amor", "angle": "Retomar el camino incluye sanar cómo amas."},
            {"verse": "Sé lento para enojarte; escucha primero.", "ref": "Santiago 1:19", "theme": "control", "angle": "Tu carácter también es parte del regreso."},
            {"verse": "Pide sabiduría y Dios te la da.", "ref": "Santiago 1:5", "theme": "sabiduría", "angle": "No decidas desde la impulsividad: pide luz a Dios."},
            {"verse": "Dios no desprecia al que vuelve con sinceridad.", "ref": "Salmo 51:17", "theme": "arrepentimiento", "angle": "Un corazón humilde abre camino a la restauración."},
            {"verse": "No te afanes: aprende a confiar hoy.", "ref": "Mateo 6:34", "theme": "ansiedad", "angle": "Dios te llama a vivir un día a la vez."},
            {"verse": "En Jesús hay vida: vuelve a la fuente.", "ref": "Juan 10:10", "theme": "vida abundante", "angle": "Lo que te roba vida no merece tu lealtad."},
            {"verse": "No pagues mal con mal: rompe el ciclo.", "ref": "1 Tesalonicenses 5:15", "theme": "madurez", "angle": "Volver al camino es responder distinto, con Dios."},
            {"verse": "Si te sientes débil, la gracia te sostiene.", "ref": "2 Corintios 12:9", "theme": "gracia", "angle": "Dios se fortalece en tu debilidad cuando vuelves."},
            {"verse": "Arrepiéntete y vuelve: Dios refresca tu alma.", "ref": "Hechos 3:19", "theme": "renuevo", "angle": "El alivio llega cuando cambias de rumbo."},
            {"verse": "Elige hoy a quién servirás.", "ref": "Josué 24:15", "theme": "decisión", "angle": "Volver al camino es una decisión diaria."},
            {"verse": "No uses la libertad para dañarte: úsala para amar.", "ref": "Gálatas 5:13", "theme": "responsabilidad", "angle": "La libertad real te conduce a Dios, no al caos."},
            {"verse": "Deja el peso del pecado y corre con paciencia.", "ref": "Hebreos 12:1", "theme": "perseverancia", "angle": "Suelta lo que estorba tu avance espiritual."},
            {"verse": "Pon tus ojos en Jesús y sigue adelante.", "ref": "Hebreos 12:2", "theme": "enfoque", "angle": "No mires solo tu caída: mira a Cristo."},
            {"verse": "Guarda tu lengua y evita dolor innecesario.", "ref": "Proverbios 21:23", "theme": "dominio propio", "angle": "Dios restaura relaciones cuando controlas palabras."},
            {"verse": "La justicia te levanta; el pecado te hunde.", "ref": "Proverbios 14:34", "theme": "rectitud", "angle": "Dios te llama a una vida que edifica."},
            {"verse": "No te canses de volver: Dios te sostiene.", "ref": "Isaías 40:29", "theme": "fuerzas", "angle": "Aunque estés agotado, Dios da fuerzas al cansado."},
            {"verse": "Aprende a contentarte: Dios cuida de ti.", "ref": "Filipenses 4:11-12", "theme": "contentamiento", "angle": "La paz también se aprende con Dios."},
            {"verse": "Dios te hace nueva criatura: vive como tal.", "ref": "Efesios 4:24", "theme": "nueva vida", "angle": "Tu identidad en Dios pide hábitos nuevos."},
            {"verse": "Pide a Dios que te guíe en verdad.", "ref": "Salmo 25:5", "theme": "guía", "angle": "Volver al camino es volver a la verdad."},
            {"verse": "Dios mira tu corazón: vuelve con sinceridad.", "ref": "1 Samuel 16:7", "theme": "sinceridad", "angle": "Dios no busca apariencia, busca un corazón que regresa."},
            {"verse": "No tengas miedo: confía y obedece.", "ref": "Salmo 37:3", "theme": "confianza", "angle": "Obedecer hoy te acerca más que mil promesas."},
            {"verse": "Dios te disciplina porque te ama.", "ref": "Hebreos 12:6", "theme": "corrección", "angle": "La corrección no es rechazo: es amor que endereza."},
            {"verse": "Permanece firme y no vuelvas atrás.", "ref": "1 Corintios 15:58", "theme": "constancia", "angle": "Volver es bueno; permanecer es mejor: con Dios se puede."},
            {"verse": "Dios es fiel: Él completa lo que empezó.", "ref": "Filipenses 1:6", "theme": "proceso", "angle": "No te desesperes: Dios está trabajando en ti."},
            {"verse": "La bondad de Dios te guía al arrepentimiento.", "ref": "Romanos 2:4", "theme": "bondad", "angle": "Dios te atrae con amor, no con humillación."},
            {"verse": "Dios te limpia y te devuelve firmeza interior.", "ref": "Salmo 51:12", "theme": "restauración", "angle": "La alegría vuelve cuando vuelves a Dios."},
            {"verse": "Obedece hoy: la obediencia protege tu futuro.", "ref": "Deuteronomio 30:19-20", "theme": "elección", "angle": "Dios te llama a escoger vida hoy."},
        ],
    },

    "night": {
        "tag": "EN FAMILIA",
        "headline": "Gracias por el día",
        "items": [
            {"verse": "Duerme en paz: Dios te hace vivir confiado.", "ref": "Salmo 4:8", "theme": "paz", "angle": "La paz no viene de controlarlo todo, sino de confiar en Dios."},
            {"verse": "Dios es refugio: descansa bajo su cuidado.", "ref": "Salmo 91:1", "theme": "protección", "angle": "Cierra el día sabiendo que Dios te cubre."},
            {"verse": "Ven a Jesús y recibe descanso para tu alma.", "ref": "Mateo 11:28", "theme": "descanso", "angle": "Dios no te pide fuerza: te ofrece descanso."},
            {"verse": "Entrega tu carga y recibe paz en el corazón.", "ref": "Filipenses 4:7", "theme": "paz mental", "angle": "La paz de Dios guarda tu mente cuando sueltas la ansiedad."},
            {"verse": "Perdona antes de dormir: suelta el enojo.", "ref": "Efesios 4:26", "theme": "perdón", "angle": "Cierra el día en paz: tu casa lo necesita."},
            {"verse": "Ama y soporta: el amor cubre mucho.", "ref": "1 Pedro 4:8", "theme": "amor", "angle": "El amor sana el ambiente y restaura relaciones."},
            {"verse": "Dios te da paz; no vivas dominado por temor.", "ref": "Juan 14:27", "theme": "paz", "angle": "Aunque el día fue pesado, Dios puede darte calma."},
            {"verse": "Dios da sueño y descanso a quien ama.", "ref": "Salmo 127:2", "theme": "descanso", "angle": "No te consumas: descansa en Dios."},
            {"verse": "Dios es tu pastor: te guía a descanso.", "ref": "Salmo 23:2-3", "theme": "restauración", "angle": "Dios puede restaurarte incluso al final del día."},
            {"verse": "Dios oye tu clamor cuando estás afligido.", "ref": "Salmo 34:17", "theme": "consuelo", "angle": "No te duermas con dolor sin hablar con Dios."},
            {"verse": "Dios sana heridas y restaura tu interior.", "ref": "Salmo 147:3", "theme": "sanidad", "angle": "Tu dolor no es el final: Dios puede curar."},
            {"verse": "Confía: Dios guarda tu salida y tu entrada.", "ref": "Salmo 121:7-8", "theme": "protección", "angle": "Dios cuida de ti y de los tuyos."},
            {"verse": "Dios fortalece al cansado: suéltalo en oración.", "ref": "Isaías 40:29", "theme": "fortaleza", "angle": "Tu cansancio no asusta a Dios: se lo puedes entregar."},
            {"verse": "Si hoy fallaste, hay perdón al confesar.", "ref": "1 Juan 1:9", "theme": "perdón", "angle": "No te vayas a dormir lejos por culpa: vuelve."},
            {"verse": "Dios te sostiene aun cuando te sientes débil.", "ref": "Salmo 73:26", "theme": "fuerza", "angle": "Dios es tu fuerza cuando ya no te queda nada."},
            {"verse": "Dios es tu amparo: no estás solo.", "ref": "Salmo 46:1", "theme": "refugio", "angle": "Tu casa puede descansar bajo su cuidado."},
            {"verse": "Que Dios guarde tu mente en paz esta noche.", "ref": "Isaías 26:3", "theme": "paz mental", "angle": "La paz crece cuando tu mente se ancla en Dios."},
            {"verse": "Dios te da descanso; suelta la ansiedad.", "ref": "1 Pedro 5:7", "theme": "ansiedad", "angle": "No cargues lo que Dios quiere cargar contigo."},
            {"verse": "Dios te acompaña en la oscuridad también.", "ref": "Salmo 139:11-12", "theme": "cercanía", "angle": "Aun en la noche, Dios no se aleja."},
            {"verse": "Haz paz con Dios y con tu familia hoy.", "ref": "Colosenses 3:13", "theme": "perdón y familia", "angle": "Perdonar cierra el día con paz y abre un mejor mañana."},
            {"verse": "La paz de Cristo gobierna tu corazón.", "ref": "Colosenses 3:15", "theme": "paz", "angle": "Deja que Dios mande en tus emociones."},
            {"verse": "Dios te renueva: mañana será otra misericordia.", "ref": "Lamentaciones 3:23", "theme": "esperanza", "angle": "No te rindas: Dios trae nuevas misericordias."},
            {"verse": "Dios es bueno: agradécele antes de dormir.", "ref": "Salmo 136:1", "theme": "gratitud", "angle": "Agradecer sana el corazón al cerrar el día."},
            {"verse": "Dios llena tu casa de amor y paz.", "ref": "Romanos 15:13", "theme": "hogar", "angle": "Dios puede cambiar el ambiente de tu familia."},
            {"verse": "Dios cuida de ti; descansa sin temor.", "ref": "Salmo 56:3", "theme": "confianza", "angle": "El miedo no manda: la fe te guía."},
            {"verse": "En silencio y confianza hay descanso.", "ref": "Isaías 30:15", "theme": "calma", "angle": "Antes de dormir, vuelve a la quietud con Dios."},
            {"verse": "Dios te da fuerzas para mañana: duerme en paz.", "ref": "Salmo 62:5-6", "theme": "espera", "angle": "Esperar en Dios calma la mente."},
            {"verse": "Si hoy hubo tensión, Dios puede restaurar.", "ref": "Salmo 51:10", "theme": "restauración", "angle": "Pide un corazón limpio y un espíritu firme."},
            {"verse": "Dios te invita a descansar en su amor.", "ref": "Sofonías 3:17", "theme": "amor", "angle": "Dios se goza en ti y te da tranquilidad."},
            {"verse": "Dios es fiel: no te suelta esta noche.", "ref": "Hebreos 13:5", "theme": "fidelidad", "angle": "Aunque sientas soledad, Dios permanece."},
            {"verse": "Dios te guarda y te sostiene al dormir.", "ref": "Salmo 3:5", "theme": "descanso", "angle": "Puedes dormir porque Dios vela por ti."},
            {"verse": "Dios oye tu oración nocturna.", "ref": "Salmo 141:2", "theme": "oración", "angle": "Termina el día hablándole a Dios, no al miedo."},
            {"verse": "Dios trae paz al corazón que vuelve a Él.", "ref": "Salmo 37:7", "theme": "paz", "angle": "Esperar en Dios apaga el ruido interior."},
            {"verse": "Que tu hogar sea lleno de paz y gratitud.", "ref": "Salmo 133:1", "theme": "familia", "angle": "La unidad en casa es una bendición que se cuida."},
            {"verse": "Dios restaura lo que el día desgastó.", "ref": "Salmo 23:3", "theme": "restauración", "angle": "Dios puede renovar tu interior antes de dormir."},
            {"verse": "Dios te enseña a descansar en su cuidado.", "ref": "Salmo 55:22", "theme": "ansiedad", "angle": "Entrega tu carga y deja que Dios sostenga."},
            {"verse": "Dios te da paz aun cuando todo está difícil.", "ref": "Juan 16:33", "theme": "paz en pruebas", "angle": "En Dios hay paz aunque el mundo apriete."},
            {"verse": "Dios te guía incluso en decisiones difíciles.", "ref": "Salmo 32:8", "theme": "dirección", "angle": "Antes de dormir, entrégale tus decisiones."},
            {"verse": "Dios te corrige con amor y te restaura.", "ref": "Hebreos 12:6", "theme": "amor y corrección", "angle": "Su corrección no es rechazo: es cuidado."},
            {"verse": "Dios te da esperanza: no cierres el día sin fe.", "ref": "Romanos 12:12", "theme": "esperanza", "angle": "La esperanza se alimenta al final del día con oración."},
            {"verse": "Dios trae consuelo y lágrimas se vuelven paz.", "ref": "Salmo 30:5", "theme": "consuelo", "angle": "La noche pasa; Dios trae mañana."},
            {"verse": "Dios te fortalece por dentro cuando vuelves.", "ref": "Efesios 3:16", "theme": "fortaleza interior", "angle": "Dios puede darte fuerzas para empezar otra vez."},
            {"verse": "Dios te llama a soltar la preocupación.", "ref": "Mateo 6:34", "theme": "ansiedad", "angle": "Un día a la vez: Dios está contigo."},
            {"verse": "Dios te invita a perdonar y sanar relaciones.", "ref": "Mateo 6:14", "theme": "perdón", "angle": "El perdón libera tu corazón y calma tu casa."},
            {"verse": "Dios te da sabiduría para manejar el día.", "ref": "Santiago 1:5", "theme": "sabiduría", "angle": "Antes de dormir, pide sabiduría para mañana."},
            {"verse": "Dios cuida tu mente: elige pensamientos de bien.", "ref": "Filipenses 4:8", "theme": "mente", "angle": "Lo que piensas antes de dormir afecta tu paz."},
            {"verse": "Dios es tu luz incluso cuando todo se apaga.", "ref": "Salmo 27:1", "theme": "seguridad", "angle": "La oscuridad no domina cuando Dios es tu luz."},
            {"verse": "Dios te sostiene cuando tu corazón está cansado.", "ref": "Salmo 94:19", "theme": "consuelo", "angle": "Dios puede calmar el torbellino interior."},
            {"verse": "Dios te da alegría: agradece y descansa.", "ref": "1 Tesalonicenses 5:16-18", "theme": "gratitud", "angle": "Agradecer antes de dormir ordena el corazón."},
            {"verse": "Dios te llama a hacer paz con tu prójimo.", "ref": "Romanos 12:18", "theme": "paz con otros", "angle": "Haz lo posible por vivir en paz: tu alma lo agradece."},
            {"verse": "Dios te cubre: descansa sin miedo.", "ref": "Salmo 91:4", "theme": "protección", "angle": "Tu seguridad última está en Dios."},
            {"verse": "Dios trae calma al que confía.", "ref": "Proverbios 3:24-26", "theme": "descanso", "angle": "Tu corazón puede dormir en confianza."},
            {"verse": "Dios restaura tu casa cuando vuelven a Él.", "ref": "Josué 24:15", "theme": "familia", "angle": "Decidir servir a Dios cambia el hogar."},
            {"verse": "Dios te da dominio propio y amor.", "ref": "2 Timoteo 1:7", "theme": "temor y control", "angle": "El miedo no manda: Dios te fortalece."},
            {"verse": "Dios te invita a descansar en su paz.", "ref": "Salmo 62:1", "theme": "paz", "angle": "Tu alma puede hallar reposo en Dios."},
            {"verse": "Dios es bueno: vuelve a Él esta noche.", "ref": "Salmo 86:5", "theme": "perdón", "angle": "Dios recibe al que vuelve con sinceridad."},
            {"verse": "Dios te da aliento: mañana puedes empezar.", "ref": "Isaías 41:10", "theme": "esperanza", "angle": "Dios sostiene tu mano aun cuando te sientes débil."},
            {"verse": "Dios ama tu hogar: termina el día en paz.", "ref": "Efesios 4:32", "theme": "familia", "angle": "La bondad y el perdón cierran el día con bendición."},
        ],
    },
}

# al inicio de src/verses.py agrega este import:
from src.verse_history import next_index

def pick(slot: str) -> dict:
    data = SLOTS[slot]
    items = data["items"]
    idx = next_index(slot, len(items), path="state/verse_history.json")
    item = items[idx]

    return {
        "slot": slot,
        "tag": data["tag"],
        "headline": data["headline"],
        "verse": item["verse"],
        "ref": item["ref"],
        "theme": item["theme"],
        "angle": item["angle"],
    }
